### ISSUE TITLE
Capitalize all fixed string values

### ISSUE THREAD

**Issue by senthuran16** [moizalicious/siddhi-json-structs#4]
There are places where fixed strings are used.

Eg: Window-Filter-Projection input type query's config is:
```
{
    type*: 'window-filter-projection',
    ...
}
```
Changing the _type_ as **WINDOW_FILTER_PROJECTION** will make it easier to define enums and use.

Every such fixed strings can be named in this manner.

_**Note:** Anyhow, comparisons are case insensitive_

**Comment by ghost** [comment]
This will not be necessary to update in the README as all the values will be checked case-insensitively anyways. You can create the JSON values with capitalized letters if you would like.

**Comment by senthuran16** [comment]
@moizalicious Values like `window-filter-projection` have dashes. I will be checking for ones with underscores (`window_filter_projection` - as case insensitive). Only these kind of changes are important.

**Comment by ghost** [comment]
Ok, will make those changes when possible. Also will make the strings to upper-case.
