### ISSUE TITLE
Accommodate 'forEvery' in all the event values of SEQUENCE query input

### ISSUE THREAD

**Issue by senthuran16** [moizalicious/siddhi-json-structs#5]
The `every` keyword can be present for the **first event** of a **Sequence Query Input type**, regardless of its type.

(The following Compiles successfully)
![image](https://user-images.githubusercontent.com/24828296/38813301-34e0cc0a-41ac-11e8-86af-dcebc3f3517f.png)

Only _counting value_ has `forEvery` key in its JSON config.
JSON configs of _ANDOR, NOTAND & NOTFOR_ values should accommodate this

**Comment by ghost** [comment]
Yes, this is an issue. But then is it ok to put `forEvery` for all of those? 

If every sequence can have the `every` keyword _**as long as it is the first one**_ then should we put in a different way in the JSON altogether to make sure only the first one has `every`. 

Or shall we just put `forEvery` in all situations and in the code level @senthuran16 and @RAVEENSR will write logic to make sure that the first one can only have the `every` statement?

**Comment by senthuran16** [comment]
If we add `every` keyword for an element that is not the first one, the Siddhi app won't compile. The first element, regardless of its type can have `forEvery`. So we will have to have `forEvery` for all the types

**Comment by ghost** [comment]
Ok, will make the necessary changes.
