### ISSUE TITLE
Select in query in not mandatory.

### ISSUE THREAD

**Issue by RAVEENSR** [moizalicious/siddhi-json-structs#7]
A query without a select clause can exists.
Check in the following siddhi app in Product- SP.

```
@App:name("sample")
@App:description("Description of the plan") 

define stream TradeStream (symbol string, price double, volume long, timestamp long);

from TradeStream
insert into b;
```

**Comment by senthuran16** [comment]
`select *` clause is added when compiling the app in Siddhi run time, and the end JSON configuration will be returned with the respective configuration for `select *`
